// 전자담배 상품 데이터

export const CATEGORIES = {
  ALL: 'all',
  LIQUID: 'liquid',
  DEVICE: 'device',
  COIL: 'coil',
  ACCESSORY: 'accessory',
  SALE: 'sale',
};

export const CATEGORY_NAMES = {
  [CATEGORIES.ALL]: '전체',
  [CATEGORIES.LIQUID]: '액상',
  [CATEGORIES.DEVICE]: '기기',
  [CATEGORIES.COIL]: '코일',
  [CATEGORIES.ACCESSORY]: '액세서리',
  [CATEGORIES.SALE]: '할인상품',
};

// 액상 상품
export const liquidProducts = [
  {
    id: 'liquid-1',
    name: '프리미엄 망고 액상 60ml',
    category: CATEGORIES.LIQUID,
    price: 25000,
    originalPrice: 30000,
    discount: 17,
    image: null,
    description: '달콤한 열대 망고의 진한 향',
    nicotine: ['0mg', '3mg', '6mg'],
    flavor: '망고',
    volume: '60ml',
    stock: 150,
  },
  {
    id: 'liquid-2',
    name: '시원한 민트 액상 30ml',
    category: CATEGORIES.LIQUID,
    price: 18000,
    image: null,
    description: '상쾌한 민트향으로 기분전환',
    nicotine: ['0mg', '3mg', '6mg'],
    flavor: '민트',
    volume: '30ml',
    stock: 200,
  },
  {
    id: 'liquid-3',
    name: '딸기 크림 액상 60ml',
    category: CATEGORIES.LIQUID,
    price: 27000,
    originalPrice: 32000,
    discount: 16,
    image: null,
    description: '달콤한 딸기와 부드러운 크림의 조화',
    nicotine: ['0mg', '3mg', '6mg'],
    flavor: '딸기크림',
    volume: '60ml',
    stock: 120,
  },
  {
    id: 'liquid-4',
    name: '블루베리 액상 30ml',
    category: CATEGORIES.LIQUID,
    price: 19000,
    image: null,
    description: '새콤달콤한 블루베리 맛',
    nicotine: ['0mg', '3mg', '6mg'],
    flavor: '블루베리',
    volume: '30ml',
    stock: 180,
  },
  {
    id: 'liquid-5',
    name: '수박 액상 60ml',
    category: CATEGORIES.LIQUID,
    price: 24000,
    image: null,
    description: '시원한 수박향',
    nicotine: ['0mg', '3mg', '6mg'],
    flavor: '수박',
    volume: '60ml',
    stock: 100,
  },
  {
    id: 'liquid-6',
    name: '레몬에이드 액상 30ml',
    category: CATEGORIES.LIQUID,
    price: 20000,
    image: null,
    description: '상큼한 레몬에이드',
    nicotine: ['0mg', '3mg', '6mg'],
    flavor: '레몬',
    volume: '30ml',
    stock: 160,
  },
  {
    id: 'liquid-7',
    name: '포도 액상 60ml',
    category: CATEGORIES.LIQUID,
    price: 26000,
    originalPrice: 30000,
    discount: 13,
    image: null,
    description: '달콤한 포도맛',
    nicotine: ['0mg', '3mg', '6mg'],
    flavor: '포도',
    volume: '60ml',
    stock: 90,
  },
  {
    id: 'liquid-8',
    name: '복숭아 액상 30ml',
    category: CATEGORIES.LIQUID,
    price: 21000,
    image: null,
    description: '달콤한 복숭아향',
    nicotine: ['0mg', '3mg', '6mg'],
    flavor: '복숭아',
    volume: '30ml',
    stock: 140,
  },
];

// 기기 상품
export const deviceProducts = [
  {
    id: 'device-1',
    name: 'VAPE PRO X 전자담배 기기',
    category: CATEGORIES.DEVICE,
    price: 89000,
    image: null,
    description: '최신 칩셋 탑재 프리미엄 기기',
    battery: '3000mAh',
    power: '80W',
    features: ['온도조절', '가변전압', 'LED디스플레이'],
    stock: 50,
  },
  {
    id: 'device-2',
    name: 'Pod System Mini',
    category: CATEGORIES.DEVICE,
    price: 45000,
    originalPrice: 55000,
    discount: 18,
    image: null,
    description: '휴대성 좋은 미니 팟 시스템',
    battery: '1500mAh',
    power: '25W',
    features: ['자동흡입', '충전식', '경량'],
    stock: 80,
  },
  {
    id: 'device-3',
    name: 'Classic Mod 기기',
    category: CATEGORIES.DEVICE,
    price: 120000,
    image: null,
    description: '클래식한 디자인의 고급 모드',
    battery: '4000mAh',
    power: '200W',
    features: ['듀얼배터리', 'TC모드', 'OLED'],
    stock: 30,
  },
  {
    id: 'device-4',
    name: 'Ultra Compact Pod',
    category: CATEGORIES.DEVICE,
    price: 38000,
    image: null,
    description: '초소형 휴대용 팟',
    battery: '1000mAh',
    power: '15W',
    features: ['초경량', '자동흡입'],
    stock: 100,
  },
  {
    id: 'device-5',
    name: 'Premium Box Mod',
    category: CATEGORIES.DEVICE,
    price: 150000,
    originalPrice: 180000,
    discount: 17,
    image: null,
    description: '프리미엄 박스 모드',
    battery: '5000mAh',
    power: '220W',
    features: ['듀얼배터리', 'TFT컬러', '스마트모드'],
    stock: 25,
  },
  {
    id: 'device-6',
    name: 'Starter Kit Basic',
    category: CATEGORIES.DEVICE,
    price: 55000,
    image: null,
    description: '입문자용 스타터 키트',
    battery: '2000mAh',
    power: '40W',
    features: ['올인원', '쉬운조작'],
    stock: 70,
  },
];

// 코일 상품
export const coilProducts = [
  {
    id: 'coil-1',
    name: '메쉬 코일 5개입',
    category: CATEGORIES.COIL,
    price: 15000,
    originalPrice: 20000,
    discount: 25,
    image: null,
    description: '메쉬 구조로 풍부한 맛',
    resistance: '0.15Ω',
    compatibility: 'VAPE PRO X',
    quantity: 5,
    stock: 200,
  },
  {
    id: 'coil-2',
    name: '세라믹 코일 3개입',
    category: CATEGORIES.COIL,
    price: 12000,
    image: null,
    description: '깨끗한 맛의 세라믹 코일',
    resistance: '0.5Ω',
    compatibility: 'Pod System',
    quantity: 3,
    stock: 150,
  },
  {
    id: 'coil-3',
    name: '클래식 코일 5개입',
    category: CATEGORIES.COIL,
    price: 13000,
    image: null,
    description: '오래 사용 가능한 내구성',
    resistance: '0.4Ω',
    compatibility: '범용',
    quantity: 5,
    stock: 180,
  },
  {
    id: 'coil-4',
    name: 'RBA 코일 베이스',
    category: CATEGORIES.COIL,
    price: 25000,
    image: null,
    description: '직접 감는 RBA 코일',
    resistance: '맞춤형',
    compatibility: 'Classic Mod',
    quantity: 1,
    stock: 60,
  },
  {
    id: 'coil-5',
    name: '니크롬 코일 10개입',
    category: CATEGORIES.COIL,
    price: 18000,
    originalPrice: 22000,
    discount: 18,
    image: null,
    description: '빠른 예열의 니크롬',
    resistance: '0.25Ω',
    compatibility: '범용',
    quantity: 10,
    stock: 120,
  },
  {
    id: 'coil-6',
    name: '스테인리스 코일 5개입',
    category: CATEGORIES.COIL,
    price: 16000,
    image: null,
    description: '깔끔한 맛의 스테인리스',
    resistance: '0.3Ω',
    compatibility: '범용',
    quantity: 5,
    stock: 140,
  },
];

// 액세서리 상품
export const accessoryProducts = [
  {
    id: 'accessory-1',
    name: '휴대용 케이스 세트',
    category: CATEGORIES.ACCESSORY,
    price: 12000,
    image: null,
    description: '기기와 액상을 안전하게 보관',
    material: '실리콘',
    color: ['블랙', '화이트', '레드'],
    stock: 100,
  },
  {
    id: 'accessory-2',
    name: 'USB-C 충전 케이블',
    category: CATEGORIES.ACCESSORY,
    price: 8000,
    image: null,
    description: '고속충전 지원 케이블',
    length: '1m',
    type: 'USB-C',
    stock: 200,
  },
  {
    id: 'accessory-3',
    name: '18650 배터리 2개입',
    category: CATEGORIES.ACCESSORY,
    price: 22000,
    image: null,
    description: '고용량 리튬이온 배터리',
    capacity: '3000mAh',
    voltage: '3.7V',
    stock: 80,
  },
  {
    id: 'accessory-4',
    name: '실리콘 드립팁 5개입',
    category: CATEGORIES.ACCESSORY,
    price: 9000,
    originalPrice: 12000,
    discount: 25,
    image: null,
    description: '부드러운 실리콘 드립팁',
    size: '510',
    color: ['블랙', '화이트', '투명', '레드', '블루'],
    stock: 150,
  },
  {
    id: 'accessory-5',
    name: '유리 탱크 교체용',
    category: CATEGORIES.ACCESSORY,
    price: 7000,
    image: null,
    description: '내열 유리 탱크',
    capacity: '5ml',
    compatibility: 'VAPE PRO X',
    stock: 90,
  },
  {
    id: 'accessory-6',
    name: '클리닝 브러쉬 세트',
    category: CATEGORIES.ACCESSORY,
    price: 6000,
    image: null,
    description: '기기 청소용 브러쉬 세트',
    includes: ['브러쉬 5종', '면봉'],
    stock: 120,
  },
  {
    id: 'accessory-7',
    name: '배터리 충전기',
    category: CATEGORIES.ACCESSORY,
    price: 35000,
    image: null,
    description: '4슬롯 고속 충전기',
    slots: 4,
    features: ['LCD표시', '과충전방지'],
    stock: 50,
  },
  {
    id: 'accessory-8',
    name: '코튼 위킹 세트',
    category: CATEGORIES.ACCESSORY,
    price: 10000,
    image: null,
    description: '유기농 코튼 위킹',
    quantity: '30개',
    organic: true,
    stock: 110,
  },
];

// 전체 상품 통합
export const allProducts = [
  ...liquidProducts,
  ...deviceProducts,
  ...coilProducts,
  ...accessoryProducts,
];

// 할인 상품만 필터링
export const saleProducts = allProducts.filter((product) => product.discount);
