// 포토리뷰 데이터
export const allReviews = [
  {
    id: 1,
    author: '김**',
    product: '프리미엄 망고 액상',
    rating: 5,
    content: '맛이 정말 좋아요! 재구매 의사 100%입니다. 향도 진하고 오래가서 만족스럽습니다.',
    image: null,
    date: '2024.01.15',
  },
  {
    id: 2,
    author: '이**',
    product: 'VAPE PRO X',
    rating: 5,
    content: '디자인도 예쁘고 성능도 만족스럽습니다. 배터리 용량도 충분해요.',
    image: null,
    date: '2024.01.14',
  },
  {
    id: 3,
    author: '박**',
    product: '메쉬 코일',
    rating: 4,
    content: '가성비 좋네요. 맛도 깔끔하고 연기량도 적당합니다.',
    image: null,
    date: '2024.01.13',
  },
  {
    id: 4,
    author: '최**',
    product: '휴대용 케이스',
    rating: 5,
    content: '품질이 생각보다 훨씬 좋습니다. 튼튼하고 디자인도 심플해요.',
    image: null,
    date: '2024.01.12',
  },
  {
    id: 5,
    author: '정**',
    product: '딸기 요거트 액상',
    rating: 5,
    content: '달콤하고 상큼한 맛이 일품입니다. 강추!',
    image: null,
    date: '2024.01.11',
  },
  {
    id: 6,
    author: '강**',
    product: 'VAPE MINI',
    rating: 4,
    content: '휴대하기 좋고 가볍습니다. 입문용으로 추천해요.',
    image: null,
    date: '2024.01.10',
  },
  {
    id: 7,
    author: '윤**',
    product: '멘솔 액상',
    rating: 5,
    content: '청량감이 끝내줍니다. 여름에 특히 좋을 것 같아요.',
    image: null,
    date: '2024.01.09',
  },
  {
    id: 8,
    author: '조**',
    product: '세라믹 코일 팩',
    rating: 4,
    content: '내구성이 좋고 맛도 깔끔합니다.',
    image: null,
    date: '2024.01.08',
  },
  {
    id: 9,
    author: '임**',
    product: '블루베리 액상',
    rating: 5,
    content: '자연스러운 블루베리 향이 좋아요. 재구매 예정입니다.',
    image: null,
    date: '2024.01.07',
  },
  {
    id: 10,
    author: '한**',
    product: 'VAPE PREMIUM',
    rating: 5,
    content: '고급스러운 디자인과 뛰어난 성능. 가격대비 만족스럽습니다.',
    image: null,
    date: '2024.01.06',
  },
  {
    id: 11,
    author: '오**',
    product: '청포도 액상',
    rating: 4,
    content: '은은한 청포도 향이 매력적입니다.',
    image: null,
    date: '2024.01.05',
  },
  {
    id: 12,
    author: '서**',
    product: '충전 케이블',
    rating: 5,
    content: '충전 속도가 빠르고 내구성도 좋습니다.',
    image: null,
    date: '2024.01.04',
  },
];
